spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
